#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: 356da62
#
Name     : R-withr
Version  : 3.0.1
Release  : 90
URL      : https://cran.r-project.org/src/contrib/withr_3.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/withr_3.0.1.tar.gz
Summary  : Run Code 'With' Temporarily Modified Global State
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
modified global state. Many of these functions were originally a part
    of the 'devtools' package, this provides a simple package with limited
    dependencies to provide access to these functions.

%prep
%setup -q -n withr
pushd ..
cp -a withr buildavx2
popd
pushd ..
cp -a withr buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722447138

%install
export SOURCE_DATE_EPOCH=1722447138
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/withr/DESCRIPTION
/usr/lib64/R/library/withr/INDEX
/usr/lib64/R/library/withr/LICENSE
/usr/lib64/R/library/withr/Meta/Rd.rds
/usr/lib64/R/library/withr/Meta/features.rds
/usr/lib64/R/library/withr/Meta/hsearch.rds
/usr/lib64/R/library/withr/Meta/links.rds
/usr/lib64/R/library/withr/Meta/nsInfo.rds
/usr/lib64/R/library/withr/Meta/package.rds
/usr/lib64/R/library/withr/Meta/vignette.rds
/usr/lib64/R/library/withr/NAMESPACE
/usr/lib64/R/library/withr/NEWS.md
/usr/lib64/R/library/withr/R/withr
/usr/lib64/R/library/withr/R/withr.rdb
/usr/lib64/R/library/withr/R/withr.rdx
/usr/lib64/R/library/withr/doc/index.html
/usr/lib64/R/library/withr/doc/withr.R
/usr/lib64/R/library/withr/doc/withr.Rmd
/usr/lib64/R/library/withr/doc/withr.html
/usr/lib64/R/library/withr/help/AnIndex
/usr/lib64/R/library/withr/help/aliases.rds
/usr/lib64/R/library/withr/help/figures/README-unnamed-chunk-3-1.png
/usr/lib64/R/library/withr/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/withr/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/withr/help/figures/logo.png
/usr/lib64/R/library/withr/help/paths.rds
/usr/lib64/R/library/withr/help/withr.rdb
/usr/lib64/R/library/withr/help/withr.rdx
/usr/lib64/R/library/withr/html/00Index.html
/usr/lib64/R/library/withr/html/R.css
/usr/lib64/R/library/withr/tests/testthat.R
/usr/lib64/R/library/withr/tests/testthat/_snaps/defer.md
/usr/lib64/R/library/withr/tests/testthat/_snaps/language.md
/usr/lib64/R/library/withr/tests/testthat/_snaps/path.md
/usr/lib64/R/library/withr/tests/testthat/_snaps/standalone-defer.md
/usr/lib64/R/library/withr/tests/testthat/helper.R
/usr/lib64/R/library/withr/tests/testthat/test-collate.R
/usr/lib64/R/library/withr/tests/testthat/test-connection.R
/usr/lib64/R/library/withr/tests/testthat/test-db.R
/usr/lib64/R/library/withr/tests/testthat/test-defer.R
/usr/lib64/R/library/withr/tests/testthat/test-devices.R
/usr/lib64/R/library/withr/tests/testthat/test-env.R
/usr/lib64/R/library/withr/tests/testthat/test-file.R
/usr/lib64/R/library/withr/tests/testthat/test-language.R
/usr/lib64/R/library/withr/tests/testthat/test-local.R
/usr/lib64/R/library/withr/tests/testthat/test-local_.R
/usr/lib64/R/library/withr/tests/testthat/test-locale.R
/usr/lib64/R/library/withr/tests/testthat/test-namespace.R
/usr/lib64/R/library/withr/tests/testthat/test-options.R
/usr/lib64/R/library/withr/tests/testthat/test-par.R
/usr/lib64/R/library/withr/tests/testthat/test-path.R
/usr/lib64/R/library/withr/tests/testthat/test-rng.R
/usr/lib64/R/library/withr/tests/testthat/test-seed.R
/usr/lib64/R/library/withr/tests/testthat/test-sink.R
/usr/lib64/R/library/withr/tests/testthat/test-standalone-defer.R
/usr/lib64/R/library/withr/tests/testthat/test-tempdir.R
/usr/lib64/R/library/withr/tests/testthat/test-tempfile.R
/usr/lib64/R/library/withr/tests/testthat/test-timezone.R
/usr/lib64/R/library/withr/tests/testthat/test-with.R
/usr/lib64/R/library/withr/tests/testthat/test-wrap.R
